services:
  - type: web
    name: weather-mcp-server
    runtime: python
    plan: free
    buildCommand: pip install uv && uv sync
    startCommand: uv run gunicorn my_server:app -c gunicorn.conf.py
    healthCheckPath: /mcp/health
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 2
